### ISSUE TITLE
Add spdlog

### ISSUE THREAD

**Issue by terrisgit** [mjbots/bazel_deps#1]
My bazel files are here:

https://github.com/terrisgit/K-9ModernCppStarter/blob/master/WORKSPACE
https://github.com/terrisgit/K-9ModernCppStarter/tree/master/build

**Comment by jpieper** [comment]
Cool!  Are you interested / willing in making a PR against `bazel_deps` using roughly those contents?

**Comment by jpieper** [comment]
Well, anyways, how does this look? https://github.com/mjbots/bazel_deps/pull/5

**Comment by terrisgit** [comment]
Yes, I can do that
