### ISSUE TITLE
@boost//:log: Boost Detail missing

### ISSUE THREAD

**Issue by terrisgit** [mjbots/bazel_deps#15]
I added "@boost//:log" as a dependency to https://github.com/dev-guy/bazel-deps-example/blob/master/test/BUILD

It looks like the Boost Detail package needs to be added.

```bash
bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sboost_Sliblog.so: error: undefined reference to 'boost::detail::add_thread_exit_function(boost::detail::thread_exit_function_base*)'
bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sboost_Sliblog.so: error: undefined reference to 'boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'
bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Sboost_Sliblog.so: error: undefined reference to 'boost::detail::get_tss_data(void const*)'
```

**Comment by jpieper** [comment]
Want to try out #16 and see if it fixes things for you?  

Do you know how to test the contents of a specific PR?  I'd be happy to walk you through it over a chat or screenshare.

**Comment by terrisgit** [comment]
Thanks for offering! I put the commit id into repository.bzl (181203819299ff4f592e89c3e2b114c95e7a1ea7) . I'm trying it now. Still haven't sunk the day it's going to take me to write the config for vsomeip

**Comment by jpieper** [comment]
OK, well, I guess since this worked for me, I'll merge it now and if you find more problems you can open more issues.

**Comment by terrisgit** [comment]
I'll submit a PR. The dependencies between boost modules could be more accurate, as I specified in the PR comment.
