### ISSUE TITLE
OpenCV Highgui

### ISSUE THREAD

**Issue by TheButlah** [mjbots/bazel_deps#21]
Could you add support for opencv HighGUI?

**Comment by jpieper** [comment]
Thanks for your interest!  I have no current plans to add highgui support, but will help you get any patches you may develop incorporated.

**Comment by TheButlah** [comment]
Do you have tips on where to start? I'm the point person for bazel at my company but I'm very overwhelmed by this repo

**Comment by TheButlah** [comment]
Also, has this been tested with a newer version of opencv? Is it likely to work?

**Comment by jpieper** [comment]
It has only been tested with the version in the repo.  

Nominally, you just need to add the correct stanza in 
https://github.com/mjbots/bazel_deps/blob/master/tools/workspace/opencv/package.BUILD

At least one likely problem is that I don't know what windowing toolkit opencv uses.  You may have to bazel-ify it and its transitive dependencies.

Given that I haven't tried it, there may be other gotchas too.
