### ISSUE TITLE
Unable to dep on @ffmpeg

### ISSUE THREAD

**Issue by ahnm** [mjbots/bazel_deps#23]
Unable to build with @ffmpeg or @opencv//:videoio.

bazel-out/k8-fastbuild/bin/_solib_k8/_U@ffmpeg_S_S_Cavcodec_Ulib___Uexternal_Sffmpeg/libavcodec.so: error: undefined reference to 'dlclose'
bazel-out/k8-fastbuild/bin/_solib_k8/_U@ffmpeg_S_S_Cavcodec_Ulib___Uexternal_Sffmpeg/libavcodec.so: error: undefined reference to 'dlopen'
bazel-out/k8-fastbuild/bin/_solib_k8/_U@ffmpeg_S_S_Cavcodec_Ulib___Uexternal_Sffmpeg/libavcodec.so: error: undefined reference to 'dlsym'

I'm building on linux for windows subsystem, ubuntu distro.

**Comment by jpieper** [comment]
Unfortunately, I don't have any knowledge of WSL so won't be able to help. :(

**Comment by ahnm** [comment]
What distro do you use to build with?

BTW Thank you for make this.

**Comment by jpieper** [comment]
I've used ubuntu 18.04 and 20.04, but only either on bare metal or in a VM.

**Comment by ahnm** [comment]
Ok let me try that. Thanks.
