### ISSUE TITLE
Potential Pull Request for opencv highgui

### ISSUE THREAD

**Issue by ahnm** [mjbots/bazel_deps#24]
Hey all,

I forked this repos and added the opencv highgui library. It currently only compiles with QT and relies on QT already installed to the os.  If you all are interested I can make a pull request.

https://github.com/ahnm/bazel_deps

**Comment by jpieper** [comment]
Thanks for the interest!

At the moment, I'm only taking things into bazel_deps that don't use the system OS, which is why highgui isn't there already.  I'm glad you were able to get something working!
