### ISSUE TITLE
Support for opencv 4

### ISSUE THREAD

**Issue by Jackey-Huo** [mjbots/bazel_deps#27]
Hi all, thank you so much for the effort of opencv bazel build, I found it extremely useful.

Is there someone who work on opencv 4? Or is there any plan to support opencv 4? Currently compile for opencv 4 is failed.

**Comment by Jackey-Huo** [comment]
@jpieper

**Comment by jpieper** [comment]
Nope, there are no plans to support OpenCV at this time.  Sorry!
