### ISSUE TITLE
Deps fail to download

### ISSUE THREAD

**Issue by lalten** [mjbots/bazel_deps#30]
Looks like this repo needs a refresh, some dependencies fail to download:

```
❯ bazel build @com_github_mjbots_bazel_deps//...
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/xxx/external/libxcb/BUILD.bazel:99:11: configurable attribute "copts" in @libxcb//:libxcb doesn't match this configuration. Would a default condition help?

Conditions checked:
 @com_github_mjbots_bazel_deps//conditions:gcc
 @com_github_mjbots_bazel_deps//conditions:clang

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @libxcb//:libxcb has configuration identifier f51144e. To inspect its configuration, run: bazel config f51144e.

For more help, see https://bazel.build/docs/configurable-attributes#faq-select-choose-condition.

WARNING: Download from https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.bz2 failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: ftp.pcre.org
ERROR: Analysis of target '@com_github_mjbots_bazel_deps//:everything' failed; build aborted: 
INFO: Elapsed time: 0.140s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (25 packages loaded, 201 targets configured)
```

**Comment by jpieper** [comment]
I don't believe those download failures are your fatal error.  In both cases, alternate URLs are present.  I think the actual problem is the one where it has not identified whether you are using gcc or clang.  Did you follow the integration directions in README?

**Comment by jpieper** [comment]
Also, it may be that there is a compatibility issue with a newer version of bazel.  I'm only testing this with 3.4.1, which I realize is old, but I don't have reason to upgrade yet.

**Comment by lalten** [comment]
Oh, you're right. I didn't read carefully enough. Looks like the select in the lines below has no default, and it does not find the other two to apply.
https://github.com/mjbots/bazel_deps/blob/4af075fe9549f26063bbd6b3f2d039d9854fbdca/tools/workspace/libxcb/package.BUILD#L129-L134

**Comment by lalten** [comment]
My setup is this in the WORKSPACE:
```
http_archive(
    name = "com_github_mjbots_bazel_deps",
    sha256 = "0b3b485d411b44dc7f0d20b895b11f85ca592862c9f3a1d84d584f30c1152200",
    strip_prefix = "bazel_deps-4af075fe9549f26063bbd6b3f2d039d9854fbdca",
    url = "https://github.com/mjbots/bazel_deps/archive/4af075fe9549f26063bbd6b3f2d039d9854fbdca.tar.gz",
)

load("@com_github_mjbots_bazel_deps//tools/workspace:default.bzl", bazel_deps_add = "add_default_repositories")

bazel_deps_add()
```

**Comment by lalten** [comment]
Looks like `build --define CLANG=true` in `.bazelrc` does the trick!

**Comment by jpieper** [comment]
What is your host and target platform?

**Comment by jpieper** [comment]
Great!

**Comment by lalten** [comment]
Next issue:
```
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/xxx/external/gstreamer/BUILD.bazel:194:8: Executing genrule @gstreamer//:bison_parser failed: (Exit 127): bash failed: error executing command (from target @gstreamer//:bison_parser) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/bin/bash: line 1: bison: command not found
```
It would be helpful if bison was bazelized ;P Will see if I'm going to install that onto the host or find another solution.

**Comment by lalten** [comment]
But thanks for your quick help on the `select` @jpieper !

**Comment by jpieper** [comment]
Yes, it looks like bison needs to be installed on the host side.  I guess most linuxes have that by default, or I would have run into it already.  Sorry, I'm not going to package bazel for you, but you're of course welcome to give it a stab!

Good luck!
