### ISSUE TITLE
GENIVI/vsomeip seems to want boost to be dynamically linked. Not sure what to do.

### ISSUE THREAD

**Issue by terrisgit** [mjbots/bazel_deps#7]
I might be able to undo this but vsomeip, which appears to build itself as a shared library, seems to want Boost to be dynamically rather than statically linked. Does bazel_deps build static or dynamic libraries?

**Comment by jpieper** [comment]
What error are you getting?  By default, bazel doesn't specify whether libraries are built dynamically or statically, and sometimes builds both.  Odds are you have a different problem.

**Comment by terrisgit** [comment]
GENIVI/vsomeip has so many cpp and header files in multiple subdirectories that I am nowhere near having a BUILD file yet. I am only looking at CMakelists and the preprocessor variable it defines. I'm going to try to get everything statically linked instead.

**Comment by jpieper** [comment]
I see.  Odds are, you can ignore the shared/static library bit, and just link everything up with bazel's `cc_library` and it will work just fine.  You would only *have* to use a shared library if `vsomeip` used `dlopen` to manually load a shared library.
